// @ts-check
// Shared HMAC sign + verify for the vcc ↔ cards402 callback channel.
//
// Protocol: HMAC-SHA256 over `${timestamp}.${orderId}.${rawBody}` using the
// shared callback_secret. The order_id is explicitly part of the signing
// payload so a signature cannot be lifted from one order's delivery and
// replayed against a different order even if the body is re-parsed or
// re-serialised on the wire.
//
// Headers:
//   X-VCC-Signature:  sha256=<hex>
//   X-VCC-Timestamp:  <unix ms>
//   X-VCC-Order-Id:   <uuid>
//
// Receiver MUST compare the signed order_id against the request URL / body
// to guarantee the caller's intent matches the signed payload.
//
// v3 is the only accepted protocol. The v1 fallback (`${timestamp}.${rawBody}`
// with no order_id binding) was removed in the 2026-04-13 adversarial audit
// (finding F6) — both services have shipped v3 since the C-3 nonce work, and
// keeping legacy acceptance widened the forgery surface for callers who knew
// only the shared secret. v2 (`${ts}.${orderId}.${body}`, no nonce) is still
// accepted as a transitional fallback because it still binds the order_id.
//
// Audit findings addressed: A-11 (extract to shared lib), C-4 (sign
// order_id), C-5 (configurable skew), C-13 (caller-enforced secret length),
// F6 (drop v1 acceptance).

const crypto = require('crypto');

// Default replay-protection window. Callers can override per-call for tests.
const DEFAULT_SKEW_MS = 10 * 60 * 1000; // 10 min

// F1-hmac (2026-04-15): Strict digits-only timestamp format. parseInt
// is lax — `parseInt('1700000000000abc', 10)` returns 1700000000000, so
// the skew check passes while signCallback hashes the full string
// including the garbage. A legitimate signer never produces such input,
// but a buggy client library (unstripped whitespace, trailing newline,
// locale-formatted number with a dot) creates a sig that verifyCallback
// would reject while the skew check happily accepts it — hard-to-debug
// asymmetry. Enforcing `^\d+$` locks sign and verify to the same
// canonical form. Applied at both signCallback (throw) and verifyCallback
// (missing_fields) so the constraint is symmetric.
const TIMESTAMP_STRICT = /^\d+$/;

// F2-hmac (2026-04-15): Canonicalization guard for the orderId and
// nonce fields.
//
// The signing payload uses `.` as a component delimiter:
//   v3: ${ts}.${orderId}.${nonce}.${rawBody}
//   v2: ${ts}.${orderId}.${rawBody}
//
// If any field ITSELF contains a `.`, the split is ambiguous. Concretely:
// signing v3 for (orderId="alice", nonce="bob") is byte-identical to
// signing v2 for orderId="alice.bob" over the same body. The HMAC output
// is the same 64-char hex string for both semantic meanings. A compromised
// v2 signer (or a signer that accepts operator-chosen orderIds without
// validation) becomes a v3 forgery oracle: sign v2 with orderId="X.Y",
// lift the hex, present it as v3 with (orderId="X", nonce="Y"). Today's
// orderIds and nonces are UUIDs (no dots), so no live exploit exists,
// but the library has no defense against a future caller with a
// permissive identifier scheme (slugs, paths, labels, operator-chosen
// keys). CR/LF and C0 control chars are rejected for the same reason as
// email header injection: a field value spanning multiple lines is a
// strong signal of tampering and has no legitimate use.
const FIELD_UNSAFE = /[.\r\n\x00-\x1f]/;

/**
 * @param {string} name   Field name, for error message.
 * @param {string} value  Field value.
 * @throws if value is missing, non-string, or contains an unsafe char.
 */
function assertCanonicalField(name, value) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(`${name} must be a non-empty string`);
  }
  if (FIELD_UNSAFE.test(value)) {
    throw new Error(
      `${name} must not contain '.', CR, LF, or C0 control chars ` +
        `(HMAC payload canonicalization — see F2-hmac)`,
    );
  }
}

/**
 * Verify-time counterpart of assertCanonicalField: returns true if the
 * field is safe, false otherwise. Callers translate false into a
 * bad_signature / missing_fields result rather than throwing, so a
 * hostile caller cannot weaponise canonicalization failures into a
 * 500 that knocks the handler offline.
 * @param {string | undefined | null} value
 */
function isCanonicalField(value) {
  return typeof value === 'string' && value.length > 0 && !FIELD_UNSAFE.test(value);
}

/**
 * Produce the hex HMAC for a callback.
 *
 * v3 payload (when nonce is provided): `${timestamp}.${orderId}.${nonce}.${rawBody}`
 * v2 payload (no nonce):               `${timestamp}.${orderId}.${rawBody}`
 *
 * The nonce is a per-job UUID generated by cards402 at invoice time and
 * stored on both the order (cards402) and the job (vcc). Including it in
 * the signing payload means a leaked VCC_CALLBACK_SECRET alone is not
 * enough to forge a callback — the attacker also needs the per-order nonce.
 * Audit C-3.
 *
 * @param {object} args
 * @param {string} args.secret      Shared callback secret.
 * @param {string} args.timestamp   Unix epoch ms as a string (caller-owned).
 * @param {string} args.orderId     Order UUID the callback is about.
 * @param {string} args.rawBody     Canonicalised raw request body (string).
 * @param {string} [args.nonce]     Per-job nonce (v3). Omit for v2 compat.
 * @returns {string} hex digest
 */
function signCallback({ secret, timestamp, orderId, rawBody, nonce }) {
  if (!secret) throw new Error('signCallback: secret is required');
  if (!timestamp) throw new Error('signCallback: timestamp is required');
  if (!orderId) throw new Error('signCallback: orderId is required');
  if (rawBody === null || rawBody === undefined)
    throw new Error('signCallback: rawBody is required');
  // F1-hmac: reject non-digit timestamps so sign and verify agree on
  // the canonical byte form.
  if (typeof timestamp !== 'string' || !TIMESTAMP_STRICT.test(timestamp)) {
    throw new Error(`signCallback: timestamp must be digits-only string, got ${typeof timestamp}`);
  }
  // F2-hmac: reject orderId/nonce containing the `.` delimiter or
  // control chars. Prevents HMAC-payload-split canonicalization attacks.
  assertCanonicalField('orderId', orderId);
  if (nonce !== undefined) assertCanonicalField('nonce', nonce);
  const payload = nonce
    ? `${timestamp}.${orderId}.${nonce}.${rawBody}`
    : `${timestamp}.${orderId}.${rawBody}`;
  return crypto.createHmac('sha256', secret).update(payload).digest('hex');
}

/**
 * Verify an incoming callback signature.
 *
 * Tries protocol versions in descending order:
 *   v3 (nonce):    `${ts}.${orderId}.${nonce}.${body}` — strongest, per-job scoped
 *   v2 (no nonce): `${ts}.${orderId}.${body}`          — order-id-bound
 *
 * v1 (`${ts}.${body}` with no order_id binding) was removed in F6 — both
 * services have shipped v3 since the C-3 nonce work, and the v1 branch
 * was a forgery surface for any caller who knew only the shared secret.
 *
 * Returns one of:
 *   { ok: true, version: 3 }        — v3 with nonce validated
 *   { ok: true, version: 2 }        — v2 signature validated
 *   { ok: false, reason: 'missing_fields' }
 *   { ok: false, reason: 'timestamp_expired' }
 *   { ok: false, reason: 'bad_signature' }
 *
 * @param {object} args
 * @param {string} args.secret
 * @param {string} args.timestamp      From X-VCC-Timestamp header.
 * @param {string} args.signatureHeader Value of X-VCC-Signature header ('sha256=<hex>').
 * @param {string} [args.orderId]      From X-VCC-Order-Id header.
 * @param {string} [args.nonce]        Per-job nonce from X-VCC-Nonce header (v3).
 * @param {string} args.rawBody        Raw request body captured by express verify.
 * @param {number} [args.maxSkewMs]    Replay window.
 * @param {number} [args.now]          Injected clock for tests.
 * @param {boolean} [args.requireV3]   If true, v2 fallback is disabled — a
 *                                     v3-enrolled order will NOT accept a
 *                                     signature that only binds order_id.
 *                                     Callers set this whenever the order's
 *                                     stored nonce or per-order secret is
 *                                     non-NULL, so a downgrade attack on the
 *                                     header fields can't reach v2 validation
 *                                     regardless of handler-side checks.
 *                                     Audit F1-vcc-callback.
 */
function verifyCallback({
  secret,
  timestamp,
  signatureHeader,
  orderId,
  nonce,
  rawBody,
  maxSkewMs = DEFAULT_SKEW_MS,
  now = Date.now(),
  requireV3 = false,
}) {
  if (!secret || !signatureHeader || !timestamp || rawBody === null || rawBody === undefined) {
    return { ok: false, reason: 'missing_fields' };
  }

  // F1-hmac: strict digits-only timestamp format. Must come before the
  // parseInt skew check so non-canonical inputs (e.g. '1700000000000abc',
  // '  1700000000000  ', '1700000000000.5') are rejected outright rather
  // than slipping through the skew check while desynchronising the
  // payload byte form between sign and verify.
  if (typeof timestamp !== 'string' || !TIMESTAMP_STRICT.test(timestamp)) {
    return { ok: false, reason: 'missing_fields' };
  }

  const ts = parseInt(timestamp, 10);
  if (!Number.isFinite(ts)) return { ok: false, reason: 'missing_fields' };
  if (Math.abs(now - ts) > maxSkewMs) return { ok: false, reason: 'timestamp_expired' };

  // Accept either "sha256=<hex>" or "<hex>" for forgiving parsers.
  const provided = String(signatureHeader).replace(/^sha256=/, '');
  if (!/^[0-9a-f]+$/i.test(provided)) return { ok: false, reason: 'bad_signature' };

  // F2-hmac: canonicalization guard on orderId/nonce. Reject any caller
  // whose fields contain the HMAC payload delimiter or control chars
  // rather than passing them through to signCallback (which would throw
  // inside the try/catch and then fall through to v2 anyway). Mapping
  // to bad_signature is the right verdict: a request that can't even
  // produce a well-formed signing payload cannot have a valid sig.
  if (orderId !== undefined && orderId !== null && !isCanonicalField(orderId)) {
    return { ok: false, reason: 'bad_signature' };
  }
  if (nonce !== undefined && nonce !== null && !isCanonicalField(nonce)) {
    return { ok: false, reason: 'bad_signature' };
  }

  // v3: order_id + nonce in the signing payload. Strongest — per-job scoped.
  if (orderId && nonce) {
    const expectedV3 = signCallback({
      secret,
      timestamp,
      orderId,
      rawBody,
      nonce,
    });
    if (safeEqHex(provided, expectedV3)) return { ok: true, version: 3 };
  }

  // requireV3 short-circuits the v2 fallback. Used by vcc-callback when the
  // order row has a stored nonce or per-order secret — v3 is mandatory and
  // a v2 signature is a downgrade attempt.
  if (requireV3) {
    return { ok: false, reason: 'bad_signature' };
  }

  // v2: order_id in the signing payload, no nonce. Transitional fallback —
  // still order-id-bound so it can't be replayed across orders.
  if (orderId) {
    const expectedV2 = signCallback({
      secret,
      timestamp,
      orderId,
      rawBody,
    });
    if (safeEqHex(provided, expectedV2)) return { ok: true, version: 2 };
  }

  return { ok: false, reason: 'bad_signature' };
}

/**
 * Timing-safe hex-string comparison. Returns false for any non-hex input
 * or length mismatch. Wraps `crypto.timingSafeEqual` for the actual compare
 * so the success path runs in constant time relative to the buffer length.
 */
function safeEqHex(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  if (a.length !== b.length) return false;
  if (!/^[0-9a-f]+$/i.test(a) || !/^[0-9a-f]+$/i.test(b)) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(a, 'hex'), Buffer.from(b, 'hex'));
  } catch {
    return false;
  }
}

module.exports = {
  signCallback,
  verifyCallback,
  safeEqHex,
  DEFAULT_SKEW_MS,
};
