// @ts-check
// Shared HMAC sign + verify for the vcc ↔ cards402 callback channel.
//
// Protocol: HMAC-SHA256 over `${timestamp}.${orderId}.${rawBody}` using the
// shared callback_secret. The order_id is explicitly part of the signing
// payload so a signature cannot be lifted from one order's delivery and
// replayed against a different order even if the body is re-parsed or
// re-serialised on the wire.
//
// Headers:
//   X-VCC-Signature:  sha256=<hex>
//   X-VCC-Timestamp:  <unix ms>
//   X-VCC-Order-Id:   <uuid>
//
// Receiver MUST compare the signed order_id against the request URL / body
// to guarantee the caller's intent matches the signed payload.
//
// v3 is the only accepted protocol. The v1 fallback (`${timestamp}.${rawBody}`
// with no order_id binding) was removed in the 2026-04-13 adversarial audit
// (finding F6) — both services have shipped v3 since the C-3 nonce work, and
// keeping legacy acceptance widened the forgery surface for callers who knew
// only the shared secret. v2 (`${ts}.${orderId}.${body}`, no nonce) is still
// accepted as a transitional fallback because it still binds the order_id.
//
// Audit findings addressed: A-11 (extract to shared lib), C-4 (sign
// order_id), C-5 (configurable skew), C-13 (caller-enforced secret length),
// F6 (drop v1 acceptance).

const crypto = require('crypto');

// Default replay-protection window. Callers can override per-call for tests.
const DEFAULT_SKEW_MS = 10 * 60 * 1000; // 10 min

/**
 * Produce the hex HMAC for a callback.
 *
 * v3 payload (when nonce is provided): `${timestamp}.${orderId}.${nonce}.${rawBody}`
 * v2 payload (no nonce):               `${timestamp}.${orderId}.${rawBody}`
 *
 * The nonce is a per-job UUID generated by cards402 at invoice time and
 * stored on both the order (cards402) and the job (vcc). Including it in
 * the signing payload means a leaked VCC_CALLBACK_SECRET alone is not
 * enough to forge a callback — the attacker also needs the per-order nonce.
 * Audit C-3.
 *
 * @param {object} args
 * @param {string} args.secret      Shared callback secret.
 * @param {string} args.timestamp   Unix epoch ms as a string (caller-owned).
 * @param {string} args.orderId     Order UUID the callback is about.
 * @param {string} args.rawBody     Canonicalised raw request body (string).
 * @param {string} [args.nonce]     Per-job nonce (v3). Omit for v2 compat.
 * @returns {string} hex digest
 */
function signCallback({ secret, timestamp, orderId, rawBody, nonce }) {
  if (!secret) throw new Error('signCallback: secret is required');
  if (!timestamp) throw new Error('signCallback: timestamp is required');
  if (!orderId) throw new Error('signCallback: orderId is required');
  if (rawBody === null || rawBody === undefined)
    throw new Error('signCallback: rawBody is required');
  const payload = nonce
    ? `${timestamp}.${orderId}.${nonce}.${rawBody}`
    : `${timestamp}.${orderId}.${rawBody}`;
  return crypto.createHmac('sha256', secret).update(payload).digest('hex');
}

/**
 * Verify an incoming callback signature.
 *
 * Tries protocol versions in descending order:
 *   v3 (nonce):    `${ts}.${orderId}.${nonce}.${body}` — strongest, per-job scoped
 *   v2 (no nonce): `${ts}.${orderId}.${body}`          — order-id-bound
 *
 * v1 (`${ts}.${body}` with no order_id binding) was removed in F6 — both
 * services have shipped v3 since the C-3 nonce work, and the v1 branch
 * was a forgery surface for any caller who knew only the shared secret.
 *
 * Returns one of:
 *   { ok: true, version: 3 }        — v3 with nonce validated
 *   { ok: true, version: 2 }        — v2 signature validated
 *   { ok: false, reason: 'missing_fields' }
 *   { ok: false, reason: 'timestamp_expired' }
 *   { ok: false, reason: 'bad_signature' }
 *
 * @param {object} args
 * @param {string} args.secret
 * @param {string} args.timestamp      From X-VCC-Timestamp header.
 * @param {string} args.signatureHeader Value of X-VCC-Signature header ('sha256=<hex>').
 * @param {string} [args.orderId]      From X-VCC-Order-Id header.
 * @param {string} [args.nonce]        Per-job nonce from X-VCC-Nonce header (v3).
 * @param {string} args.rawBody        Raw request body captured by express verify.
 * @param {number} [args.maxSkewMs]    Replay window.
 * @param {number} [args.now]          Injected clock for tests.
 */
function verifyCallback({
  secret,
  timestamp,
  signatureHeader,
  orderId,
  nonce,
  rawBody,
  maxSkewMs = DEFAULT_SKEW_MS,
  now = Date.now(),
}) {
  if (!secret || !signatureHeader || !timestamp || rawBody === null || rawBody === undefined) {
    return { ok: false, reason: 'missing_fields' };
  }

  const ts = parseInt(timestamp, 10);
  if (!Number.isFinite(ts)) return { ok: false, reason: 'missing_fields' };
  if (Math.abs(now - ts) > maxSkewMs) return { ok: false, reason: 'timestamp_expired' };

  // Accept either "sha256=<hex>" or "<hex>" for forgiving parsers.
  const provided = String(signatureHeader).replace(/^sha256=/, '');
  if (!/^[0-9a-f]+$/i.test(provided)) return { ok: false, reason: 'bad_signature' };

  // v3: order_id + nonce in the signing payload. Strongest — per-job scoped.
  if (orderId && nonce) {
    const expectedV3 = signCallback({
      secret,
      timestamp,
      orderId,
      rawBody,
      nonce,
    });
    if (safeEqHex(provided, expectedV3)) return { ok: true, version: 3 };
  }

  // v2: order_id in the signing payload, no nonce. Transitional fallback —
  // still order-id-bound so it can't be replayed across orders.
  if (orderId) {
    const expectedV2 = signCallback({
      secret,
      timestamp,
      orderId,
      rawBody,
    });
    if (safeEqHex(provided, expectedV2)) return { ok: true, version: 2 };
  }

  return { ok: false, reason: 'bad_signature' };
}

/**
 * Timing-safe hex-string comparison. Returns false for any non-hex input
 * or length mismatch. Wraps `crypto.timingSafeEqual` for the actual compare
 * so the success path runs in constant time relative to the buffer length.
 */
function safeEqHex(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  if (a.length !== b.length) return false;
  if (!/^[0-9a-f]+$/i.test(a) || !/^[0-9a-f]+$/i.test(b)) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(a, 'hex'), Buffer.from(b, 'hex'));
  } catch {
    return false;
  }
}

module.exports = {
  signCallback,
  verifyCallback,
  safeEqHex,
  DEFAULT_SKEW_MS,
};
