// @ts-check
// Canonical "create an orders row" helper.
//
// Extracted from api/orders.js so that any future API surface (MPP is the
// first) inserts orders through the same code path. The alternative —
// hand-rolled INSERT statements scattered across modules — is how the
// v1_orders and MPP paths end up drifting silently on column additions
// or status-value changes. One helper, one source of truth.
//
// Deliberately scoped to the "pending_payment" case only. The awaiting-
// approval and sandbox-delivered insert shapes in api/orders.js use
// different column subsets and don't benefit from sharing with MPP.

const db = require('../db');

/**
 * @typedef {object} InsertPendingPaymentOrderOpts
 * @property {string} id - UUID, generated by the caller.
 * @property {string} amount_usdc - Decimal string, e.g. '10.00'.
 * @property {string|null} expected_xlm_amount - Pre-quoted XLM amount (if provided).
 * @property {string} api_key_id - FK to api_keys.id.
 * @property {string|null} webhook_url - Optional webhook override for this order.
 * @property {string|null} metadata - Pre-serialised JSON string.
 * @property {string} vcc_payment_json - Pre-serialised contract payment instructions.
 * @property {string|null} request_id - Express request id for tracing.
 * @property {'v1_orders'|'mpp'} [source] - Defaults to 'v1_orders'.
 */

/**
 * Insert a new order row in the 'pending_payment' state. Column set matches
 * the POST /v1/orders real-mode path. Throws on DB error (FK violation,
 * constraint breach, etc.) — callers wrap in a transaction if they need
 * multi-statement atomicity.
 *
 * @param {InsertPendingPaymentOrderOpts} opts
 */
function insertPendingPaymentOrder(opts) {
  const source = opts.source ?? 'v1_orders';
  db.prepare(
    `INSERT INTO orders (id, status, amount_usdc, expected_xlm_amount, api_key_id,
                         webhook_url, metadata, vcc_payment_json, request_id, source)
     VALUES (@id, 'pending_payment', @amount_usdc, @expected_xlm_amount, @api_key_id,
             @webhook_url, @metadata, @vcc_payment_json, @request_id, @source)`,
  ).run({
    id: opts.id,
    amount_usdc: opts.amount_usdc,
    expected_xlm_amount: opts.expected_xlm_amount,
    api_key_id: opts.api_key_id,
    webhook_url: opts.webhook_url,
    metadata: opts.metadata,
    vcc_payment_json: opts.vcc_payment_json,
    request_id: opts.request_id,
    source,
  });
}

module.exports = { insertPendingPaymentOrder };
